configMapGenerator:
- files:
  - application.yml
  name: cloud-sample-configmap
resources:
- ../../base
patchesStrategicMerge:
- deployment.yml
- ingress.yml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202408080544"
