apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudsample-ingress
  # annotations:
  #   kubernetes.io/ingress.class: azure/application-gateway
spec:
  ingressClassName: ingress-internal
  rules:
  - host: cloudsample.pg-aa.kubepia.net
    http:
      paths:
      - path: /
        backend:
          service:
            name: cloudsample
            port:
              number: 8080
        pathType: Prefix